spring:
  profiles:
    active: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  data:
    rest:
      base-path=/api/v1
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
server:
  port: 8080

logging:
  level:
    com.example.module11: info
  path: userService.log

service:
  description: User service
  version: 1.0 BETA
